macro(add_root_dictionaries sources)
  foreach( dictionary ${ARGN} )
    string( REGEX REPLACE "_?LinkDef.h" "" class ${dictionary} )
    root_generate_dictionary(G__${class} ${class}.h LINKDEF ${class}LinkDef.h)
    list(APPEND ${sources} G__${class}.cxx)
    install( FILES ${CMAKE_CURRENT_BINARY_DIR}/lib${class}_rdict.pcm DESTINATION ${CMAKE_INSTALL_PREFIX}/lib  )
  endforeach()
endmacro()
